version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./code:/code:delegated
      - ./confs/nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
    networks:
      - code-network
  php:
    build: .
    volumes:
      - ./code:/code:delegated
      - ./confs/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:delegated
      - ./confs/php/xdebug_enable.ini:/usr/local/etc/php/conf.d/xdebug_enable.ini:delegated
      - ./confs/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:delegated
      - ./confs/php/sendmail.ini:/usr/local/etc/php/conf.d/sendmail.ini:delegated
    networks:
      - code-network
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
    networks:
      - code-network
    volumes:
      - db_data:/var/lib/mysql:delegated
  mail:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - code-network
  elasticsearch:
    image: elasticsearch:7.1.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
volumes:
  db_data:
