version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./code:/code:delegated
      - ./confs/nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
    networks:
      - code-network
  php:
    #image: php:7.1-fpm
    build: .
    volumes:
      - ./code:/code:delegated
      - ./confs/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:delegated
      - ./confs/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:delegated
    networks:
      - code-network
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
      MYSQL_USER: root
    networks:
      - code-network
    volumes:
      - db_data:/var/lib/mysql:delegated
  maildev:
    image: djfarrelly/maildev
    ports:
      - 8282:80
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

networks:
  code-network:
    driver: bridge
volumes:
  db_data:
