version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
  php:
    #image: php:7.1-fpm
    build: .
    volumes:
      - ./code:/code
    networks:
      - code-network
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
      MYSQL_USER: root
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
